# Generated by Django 2.2 on 2021-06-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostinato', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='album',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='artist',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
